import { TextEdit, VerticalBox } from "std-widgets.slint";
import "NotoSansKR-Light.ttf";


export component MainWindow inherits Window {
    default-font-family: "NotoSansKR-Light";
    width: 200px;
    height: 200px;

    VerticalBox {
        TextEdit {
            font-size: 14px;
            text: "안녕하세요. Lorem ipsum dolor sit amet,\n consectetur adipisici elit";
            enabled: true;
            has-focus: true;
        }
    }
}